
- name: Get Database PVC name
  shell: kubectl get pvc -l app=mysql -o jsonpath='{.items[0].spec.volumeName}'
  register: mysql_pvc_name

- name: Delete Database PVC
  shell: kubectl delete pvc -l app=mysql
  when: mysql_pvc_name.stdout != ""

- name: Get Dashboard Name
  shell: gcloud monitoring dashboards list --filter="displayName=Ghost_Monitoring" --format="value(name)"
  register: output_dashboard

- name: Delete Dashboard
  shell: gcloud monitoring dashboards delete {{ output_dashboard.stdout }} --quiet
  when: output_dashboard.stdout != ""

- name: Wait for MYSQL PVC to be deleted
  shell: kubectl get pvc -l app=mysql
  register: mysqloutput
  until: mysqloutput.stdout == ""
  retries: 7
  delay: 11
