
- name: Get Database PVC name
  shell: kubectl get pvc -l app=mysql -o jsonpath='{.items[0].spec.volumeName}'
  register: mysql_pvc_name

- name: Delete Database PVC
  shell: kubectl delete pvc -l app=mysql
  when: mysql_pvc_name.stdout != ""

- name: Wait for Datbase PVC to be deleted
  shell: kubectl get pvc -l app=mysql
  register: mysqloutput
  until: mysqloutput.stdout == ""
  retries: 11
  delay: 11
