---
# Playbook to deploy Ghost and its components

- name: Install ghost
  hosts: localhost
  vars_files:
  - secretFile.yml
  roles:
  - ghost_deploy
  tags: 
  - deployGhost

- name: Update Database with Blog Admin
  hosts: localhost
  vars_files:
  - secretFile.yml
  roles:
  - update-db
  tags: 
  - updateDB

- name: Create Ghost Monitoring Dashboard
  hosts: localhost
  roles:
  - dashboard
  tags: 
  - dashboard