---
# Playbook to deploy Ghost and its components

- name: Install ghost
  hosts: localhost
  roles:
    - ghost_deploy
  tags: 
  - deployGhost

- name: Update Database with Blog Admin
  hosts: localhost
  roles:
    - update-db
  tags: 
  - updateDB