---
# Playbook to undeploy Ghost and its component
# TO DO

- name: Undeploy Ghost
  hosts: localhost
  roles:
    - {role: delete_data, when: "delete_data is defined and delete_data == 'true'"}
    - {role: ghost_undeploy}
        
  #tags:
