- name: Get MySQL Pod Name
  shell: kubectl get pods -l app=mysql -o jsonpath='{.items[0].metadata.name}'
  register: mysql_pod_name

- name: Set Pod name Fact
  set_fact:
    mysql_name_pod: "{{ mysql_pod_name.stdout }}"

- name: Update Database
  shell: kubectl exec {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" --execute="update users set name='{{ name_blogAdmin }}', password='{{ password_blogAdmin }}', email='{{ email_blogAdmin }}', status='active' where id=1;"
