---
all:
 vars:

  # GKE cluster variables
  gcp_project: ghost-ascn-369115              # ID of GCP Project
  gcp_auth_kind: serviceaccount            # Do not change
  gcp_cred_file: ghost-ascn-369115-b40df48eadef.json    # Path to service account keys (json file downloaded from GCP)

  gcp_zone: us-central1-a
  gcp_image_type: ubuntu_containerd
  gcp_machine_type: e2-small          # Can be changed if necessary
  gcp_disk_size_gb: 100                # Can be changed if necessary
  gcp_initial_node_count: 2            # Number of nodes to create. Can be changed if necessary


  # APP variables
  ghost_ip: <GHOST_SERVICE_IP>     # Needs to be updated
  ghost_port: 2368
  ghost_expose_port: 80

  mysql_name_pod: <MYSQL_POD_NAME>     # Needs to be updated

  ghost_namespace: ghostNamespace

  # Additional variables
  # ...
  
  database_name: ghost-database
  database_user: ghost-user
  database_host: mysql-service

  version_ghost: "5.14.1"

  mail: postmaster@sandbox89446cc6acf246c788b6152a1ac591dd.mailgun.org