# Login via SSH
# ssh root@your_server_ip

# Create a new user and follow prompts
# adduser <user>

# Add user to superuser group to unlock admin privileges
#usermod -aG sudo <user>

# Then log in as the new user
#su - <user>

#vinha no tutorial, fazemos????

# Add the NodeSource APT repository for Node 16
- name: Add NodeSource APT repository for Node 16
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x

#update apt cache
- name: Update system packages
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Ghost Pre Requisites
  become: true
  #flag -y meter !!!!
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ ghost_packages }}"

- name: Install Ghost-CLI
  become: true
  shell: npm install ghost-cli@latest -g

- name: Create Ghost directory
  become: true
  file:
    path: /var/www/ghost
    state: directory
    owner: user????
    mode: 0755

- name: Install Ghost
  shell: ghost install
  args:
    chdir: /var/www/ghost

- name: Insert user into Database
  mysql_query:
    login_db: ghost_db_name
    query: update users set name={{user_ghost}}, password={{password_ghost}}, email={{email_ghost}}, status='active' where id=1;


#execute mysql update
- name: Update MySQL
  become: true
  shell:  update users set name={{user_ghost:}}, password={{password_ghost}}, email={{email_ghost:}}, status='active' where id=1;
  single_transaction: yes



# replace $ to \$
