

fazer K8s cluster configuration and initialization ??????????


confirmar que isto está certo!!!!!!!


#sudo mkdir -p /mnt/data
- name: Create /mnt/data directory
  become: true
  file:
    path: /mnt/data
    state: directory
    mode: 0755


#kubectl apply -f kubectl_files/persistent-volume.yml
- name: Create Storage Class and PV objects
  k8s:
    state: present
    definition: "{{ lookup('file', kubectl_files/persistent-volume.yml) }}"


#kubectl apply -f kubectl_files/ghost/ghost-deployment.yml
- name: Create Ghost Deployment
  k8s:
    state: present
    definition: "{{ lookup('file', kubectl_files/ghost/ghost-deployment.yml) }}"

- name: Create Ghost Service
  k8s:
    state: present
    definition: "{{ lookup('file', kubectl_files/ghost/ghost-service.yml) }}"


- name: Copy database created by Ghost to dump file
  mysql_db:
    state: dump
    name: 
      - mysql #nome da base de dados????
    target: /mnt/data/dump.mysql.sql

- name: Delete Database created by Ghost
  mysql_db:
    name: mysql
    state: absent

# - name: Restore database
#   community.mysql.mysql_db:
#     name: my_db
#     state: import
#     target: /tmp/dump.sql.bz2

#kubectl apply -f kubectl_files/db/db-deployment.yml
- name: Create Database Deployment
  k8s:
    state: present
    definition: "{{ lookup('file', kubectl_files/db/db-deployment.yml) }}"

- name: Create Database PVC
  k8s:
    state: present
    definition: "{{ lookup('file', kubectl_files/db/db-pvc.yml) }}"

- name: Create Database Service
  k8s:
    state: present
    definition: "{{ lookup('file', kubectl_files/db/db-service.yml) }}"

- name: Restore database
  mysql_db:
    name: mysql
    state: import
    target: /mnt/data/dump.mysql.sql

- name: Insert Blog admin row
  mysql_query:
    login_db: mysql
    query: UPDATE users SET name=%s, password=%s, email=%s, status='active' where id=1;
    positional_args:
    - {{ user_ghost }}
    - {{ password_ghost }}
    - {{ email_ghost }}