---

# mostrar que nao ha dashboard

# dar deploy a dar skip-tag ao updateDB
# mostrar que nao ha nada das tabelas do user
# dar deploy a dar a fazer apenas a tag updateDB
# mostrar que ha dados nas tabelas do user

# mostrar dashboard

# dar undeploy sem a flag delete_data
# dar deploy normal
# dar deploy a dar skip-tag ao updateDB
# mostrar que dá para dar login

# dar undeploy com a flag delete_data
# dar deploy a dar skip-tag ao updateDB
# mostrar que nao ha nada das tabelas do user


- name: "[1]Check Dashboard"
  shell: gcloud monitoring dashboards list --filter="displayName=Ghost_Monitoring" --format="value(name)"
  register: output_dashboard
# nao e suposto aparecer nenhuma info !!!
# se aparecer fazer este comando:
# gcloud monitoring dashboards delete [name...]

- name: "[2]Display Dashboard Info"
  debug:
    msg: "{{ output_dashboard.stdout_lines }}"

- name: "[3]Deploy Ghost + Test Ghost + Create dashboard"
  include_role:
    name: '{{ roleinputvar }}' 
  loop:
    - ghost_deploy
    - test_ghost
    - dashboard
  loop_control:
    loop_var: roleinputvar

- name: "[4]Check Dashboard"
  shell: gcloud monitoring dashboards list --filter="displayName=Ghost_Monitoring" --format="value(name)"
  register: output_dashboard

- name: "[5]Display Dashboard Info"
  debug:
    msg: "{{ output_dashboard.stdout_lines }}"

- name: "[6]Check 'user' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM users;"
  register: output_user_table

- name: "[7]Display 'user' table"
  debug:
    msg: "{{ output_user_table.stdout_lines }}"

- name: "[8]Add Blog Admin"
  include_role:
    name: update-db

- name: "[9]Check 'user' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM users;"
  register: output_user_table

- name: "[10]Display 'user' table"
  debug:
    msg: "{{ output_user_table.stdout_lines }}"

- name: "[11]Undeploy Ghost (not deleting data) + Deploy Ghost (not updating DB)"
  include_role:
    name: '{{ roleinputvar }}'
  loop:
    - ghost_undeploy
    - ghost_deploy
  loop_control:
    loop_var: roleinputvar

- name: "[12]Check 'user' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM users;"
  register: output_user_table

- name: "[13]Display 'user' table"
  debug:
    msg: "{{ output_user_table.stdout_lines }}"

- name: "[14]Undeploy Ghost (deleting data) + Deploy Ghost (not updating DB)"
  include_role:
    name: '{{ roleinputvar }}'
  loop:
    - ghost_undeploy
    - delete_data
    - ghost_deploy
  loop_control:
    loop_var: roleinputvar

- name: "[15]Check 'user' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM users;"
  register: output_user_table

- name: Display 'user' table
  debug:
    msg: "{{ output_user_table.stdout_lines }}"
    
- name: "[16]Undeploy Ghost (deleting data)"
  include_role:
    name: '{{ roleinputvar }}'
  loop:
    - ghost_undeploy
    - delete_data
  loop_control:
    loop_var: roleinputvar


#
#- import_playbook: deploy-ghost.yml tags='updateDB'
#
#- name: Check 'user' table from ghost
#  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM users;"
#  register: output_user_table
#
#- name: Test if Ghost is running
#  include_role:
#    name: test_ghost
#
#- name: Deploy Ghost
#  include_role:
#    name: ghost_deploy
#
#- import_playbook: deploy-ghost.yml
#
#- name: Tests
#  hosts: localhost
#  gather_facts: yes
#  roles:
#    - { role: test_ghost }
#
#- import_playbook: undeploy-ghost.yml delete_data='true'