- name: "[1]Check Dashboard"
  shell: gcloud monitoring dashboards list --filter="displayName=Ghost_Monitoring" --format="value(name)"
  register: output_dashboard

- name: "[2]Display Dashboard Info (nao existe)"
  debug:
    msg: "{{ output_dashboard.stdout_lines }}"

- name: "[3]Deploy Ghost + Test Ghost + Create dashboard"
  include_role:
    name: '{{ roleinputvar }}' 
  loop:
    - ghost_deploy
    - test_ghost
    - dashboard
  loop_control:
    loop_var: roleinputvar

- name: "[4]Check Dashboard"
  shell: gcloud monitoring dashboards list --filter="displayName=Ghost_Monitoring" --format="value(name)"
  register: output_dashboard

- name: "[5]Display Dashboard Info (existe)"
  debug:
    msg: "{{ output_dashboard.stdout_lines }}"

- name: "[6]Check 'members' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM members;"
  register: output_members_table

- name: "[7]Display 'members' table (vazia)"
  debug:
    msg: "{{ output_members_table.stdout_lines }}"

- name: "[8]Add Member to Ghost"
  shell: kubectl exec {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" --execute="INSERT INTO members VALUES ('63bbfff67b5ec6000134fa92','411fcafd-2f9c-431f-9dd0-ed50116b1e65','tdeste@example.com','free','teste',NULL,NULL,NULL,1,0,0,NULL,'2023-01-14 17:12:03',NULL,'2023-01-14 17:12:03','63bbfff67b5ec6000134fa9b','2023-01-09 11:52:24','63bbfff67b5ec6000134fa9b');"

- name: "[9]Check 'members' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM members;"
  register: output_members_table

- name: "[10]Display 'members' table (com 1 member)"
  debug:
    msg: "{{ output_members_table.stdout_lines }}"

- name: "[11]Undeploy Ghost (not deleting data) + Deploy Ghost"
  include_role:
    name: '{{ roleinputvar }}'
  loop:
    - ghost_undeploy
    - ghost_deploy
  loop_control:
    loop_var: roleinputvar

- name: "[12]Check 'members' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM members;"
  register: output_members_table

- name: "[13]Display 'members' table (com 1 member)"
  debug:
    msg: "{{ output_members_table.stdout_lines }}"

- name: "[14]Undeploy Ghost (deleting data) + Deploy Ghost"
  include_role:
    name: '{{ roleinputvar }}'
  loop:
    - ghost_undeploy
    - delete_data
    - ghost_deploy
    - update-db
    - test_ghost
  loop_control:
    loop_var: roleinputvar

- name: "[16]Check 'members' table from ghost"
  shell: kubectl exec -it {{ mysql_name_pod }} -- mysql --user="{{ database_user }}" --password="{{ database_password }}" --database="{{ database_name }}" -e "SELECT * FROM members;"
  register: output_members_table

- name: "[17]Display 'members' table (vazia)"
  debug:
    msg: "{{ output_members_table.stdout_lines }}"
    
- name: "[18]Undeploy Ghost (deleting data)"
  include_role:
    name: '{{ roleinputvar }}'
  loop:
    - ghost_undeploy
    - delete_data
    - dashboard_delete
  loop_control:
    loop_var: roleinputvar

