
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-pvc
  labels:
    app: server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
