
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-data-pv
  labels:
    app: server
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nginx"