
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 77
        volumeMounts:
        - name: nginx-volume
          mountPath: /var/lib/nginx
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: nginx-data-pvc
