---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: ghost-database
        - name: MYSQL_USER
          value: ghost-user
        - name: MYSQL_PASSWORD
          value: password123
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-pvc-volume
          mountPath: /ur/share/nginx/html
      volumes:
      - name: mysql-pvc-volume
        persistentVolumeClaim:
          claimName: mysql-pvc

#
#    - name: mysql
#      image: mysql:8.0
#      #resources:
#      #  limits:
#      #    cpu: 10m
#      #    memory: 80Mi
#      #  requests:
#      #    cpu: 10m
#      #    memory: 80Mi
#      env:
#        - name: MYSQL_DATABASE
#          value: ghost-database
#        - name: MYSQL_USER
#          value: ghost-user
#        - name: MYSQL_PASSWORD
#          value: password123
#        - name: MYSQL_HOST
#          value: "127.0.0.1"
#      ports:
#        - containerPort: 3306
#          name: "mysql"
#      volumeMounts:
#        - mountPath: "/var/lib/mysql"
#          name: mysql-pvc-vol