---
# Deployment for MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    environment: mysql
    tier: database
spec:
  selector:
    matchLabels:
      environment: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        environment: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_HOST
          value: {{ database_host }}
        - name: MYSQL_DATABASE
          value: {{ database_name }}
        - name: MYSQL_USER
          value: {{ database_user }}
        - name: MYSQL_PASSWORD
          value: {{ database_password }} #empty assim ou assim: "" ????????????
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
