#kind: Deployment
#apiVersion: apps/v1
#metadata:
#  name: mysql-deployment
#  labels:
#    app: mysql
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: mysql
#  strategy: #???? necessario?
#    type: Recreate
#  template:
#    metadata:
#      labels:
#        app: mysql
#    spec:
#      containers:
#      - name: mysql
#        image: mysql:8.0
#        ports:
#        - containerPort: 3306
#        env:
#        - name: MYSQL_ALLOW_EMPTY_PASSWORD
#          value: "true"
#        - name: MYSQL_DATABASE
#          value: ghost-database
#        - name: MYSQL_USER
#          value: ghost-user
#        - name: MYSQL_PASSWORD
#          value: password123
#        volumeMounts:
#        - mountPath: /var/lib/mysql
#          name: mysql-data
#      volumes:
#      - name: mysql-data
#        persistentVolumeClaim:
#          claimName: mysql-data-pvc

kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: ghost-database
        - name: MYSQL_USER
          value: ghost-user
        - name: MYSQL_PASSWORD
          value: password123
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim

#
#    - name: mysql
#      image: mysql:8.0
#      #resources:
#      #  limits:
#      #    cpu: 10m
#      #    memory: 80Mi
#      #  requests:
#      #    cpu: 10m
#      #    memory: 80Mi
#      env:
#        - name: MYSQL_DATABASE
#          value: ghost-database
#        - name: MYSQL_USER
#          value: ghost-user
#        - name: MYSQL_PASSWORD
#          value: password123
#        - name: MYSQL_HOST
#          value: "127.0.0.1"
#      ports:
#        - containerPort: 3306
#          name: "mysql"
#      volumeMounts:
#        - mountPath: "/var/lib/mysql"
#          name: mysql-pvc-vol