#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pv-claim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: standard-rwo
#  resources:
#    requests:
#      storage: 10Gi




apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: {{ghost_namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-pv