
# https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  labels:
    app: mysql
spec:
  storageClassName: manual #tentar mudar para dinamico 
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"







