#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-data-pvc
#  labels:
#    app: mysql
#spec:
#  accessModes:
#  - ReadWriteOnce
#  storageClassName: manual
#  resources:
#    requests:
#      storage: 10Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi