#---
## Service for exposing Ghost
#apiVersion: v1
#kind: Service
#metadata:
#  name: ghost-service
#  labels:
#    app: ghost
#spec:
#  type: NodePort # Makes the service accessible on a static port on each Node in the cluster.
#  selector:
#    app: ghost
#  ports:
#      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
#    - targetPort: 2368 # port that containers are listening on
#      port: 2368 # port exposed internally in the cluster
#      # Optional field
#      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#      nodePort: 30077 # a static port assigned on each the node




apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368