#---
## Deployment for deploying Ghost
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: ghost
#  labels:
#    app: ghost
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: ghost
#  template:
#    metadata:
#      labels:
#        app: ghost
#    spec:
#      containers:
#      - name: ghost
#        image: ghost:5.14.1
#        ports:
#        - containerPort: 2368
#        env:
#        - name: url
#          value: http://{{ ghost_url }}
#        - name: database__client
#          value: mysql
#        - name: database__connection__host
#          value: {{ database_host }}
#        - name: database__connection__port
#          value: "3306"
#        - name: database__connection__user
#          value: {{ database_user }}
#        - name: database__connection__password
#          value: {{ database_password }}
#        - name: database__connection__database
#          value: {{ database_name }}









apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        ports:
        - containerPort: 2368
          protocol: TCP
        env:
        - name: url
          value: http://34.170.169.113:80/
        - name: database__client # tipo de database
          value: mysql
        - name: database__connection__database
          value: ghost-database
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: ghost-user
        - name: database__connection__password
          value: password123
        volumeMounts:
        - mountPath: /var/lib/ghost/content/data
          name: ghost-data
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-data-pvc