
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-data-pvc
  labels:
    app: ghost
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi