---
# Deployment for deploying Ghost
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    environment: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: ghost
  template:
    metadata:
      labels:
        environment: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        ports:
          - containerPort: 2368