#---
## Deployment for deploying Ghost
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: ghost
#  labels:
#    app: ghost
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: ghost
#  template:
#    metadata:
#      labels:
#        app: ghost
#    spec:
#      containers:
#      - name: ghost
#        image: ghost:5.14.1
#        ports:
#        - containerPort: 2368
#        env:
#        - name: url
#          value: http://{{ ghost_url }}
#        - name: database__client
#          value: mysql
#        - name: database__connection__host
#          value: {{ database_host }}
#        - name: database__connection__port
#          value: "3306"
#        - name: database__connection__user
#          value: {{ database_user }}
#        - name: database__connection__password
#          value: {{ database_password }}
#        - name: database__connection__database
#          value: {{ database_name }}









apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env:
        #- name: url
        #  value: "????"
        - name: database__client
          value: mysql
        - name: database__connection__database
          value: ghost
        - name: database__connection__host
          value: mysql
        - name: database__connection__user
          value: root
        - name: database__connection__password
          value: password123
        volumeMounts:
        - name: ghost-persistent-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-persistent-storage
        persistentVolumeClaim:
          claimName: ghost-pv-claim