apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-data-pv
  labels:
    app: ghost
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ghost"