
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        ports:
        - containerPort: 2368
          protocol: TCP
        env:
        - name: url
          value: http://34.70.239.101:80/
        - name: database__client # tipo de database
          value: mysql
        - name: database__connection__database
          value: ghost-database
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: ghost-user
        - name: database__connection__password
          value: password123
        - name: mail__transport
          value: SMTP
        - name: mail__options__service
          value: Mailgun
        - name: mail__options__host
          value: smtp.mailgun.org
        - name: mail__options__secure
          value: "true"
        - name: mail__options__auth__user
          value: postmaster@sandbox89446cc6acf246c788b6152a1ac591dd.mailgun.org
        - name: mail__options__auth__pass
          value: ecd868b8e04a9568ec1a398f85be4e2b-cc9b2d04-17488386
        - name: mail__options__port
          value: "587"
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: ghost-data
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-data-pvc
