
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:"{{ version_ghost }}"
        ports:
        - containerPort: 2368
          protocol: TCP
        env:
        - name: url
          value: http://"{{ ghost_ip }}":"{{ ghost_expose_port }}"/
        - name: database__client # tipo de database
          value: mysql
        - name: database__connection__database
          value: "{{ database_name }}"
        - name: database__connection__host
          value: "{{ database_host }}"
        - name: database__connection__user
          value: "{{ database_user }}"
        - name: database__connection__password
          value: {{ vault-database-password }}
        - name: mail__transport
          value: SMTP
        - name: mail__options__service
          value: Google
        - name: mail__options__host
          value: smtp.mailgun.org
        - name: mail__options__secure
          value: "true"
        - name: mail__options__auth__user
          value: "{{ mail }}"
        - name: mail__options__auth__pass
          value: {{ vault-mailgun-password }}
        - name: mail__options__port
          value: "587"
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: ghost-data
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-data-pvc
